FROM fluent/fluentd:v0.12-onbuild
MAINTAINER YOUR_NAME <...@...>

RUN apk add --no-cache --update --virtual .build-deps \
        sudo build-base ruby-dev \

 # cutomize following instruction as you wish
 && sudo gem install \
        fluent-plugin-secure-forward \

 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /home/fluent/.gem/ruby/2.3.0/cache/*.gem

EXPOSE 24284
