name: Scan image vulnerability

on:
  workflow_dispatch:
  schedule:
    # Sunday, 18:00 JST
    - cron:  '0 9 * * 0'

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  gem:
    name: Show bundled gems
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Show bundled gems in Fluentd image
        run: |
          # v1.19.1-debian-amd64
          IMAGE=$(make echo-all-images | cut -d' ' -f1|cut -d',' -f3)
          echo "# Show bundled gems in Fluentd image (filter)" >> $GITHUB_STEP_SUMMARY
          docker run --rm fluent/fluentd:$IMAGE gem list | grep "," >> $GITHUB_STEP_SUMMARY
          echo "# Show all bundled gems in Fluentd image (details)" >> $GITHUB_STEP_SUMMARY
          docker run --rm fluent/fluentd:$IMAGE gem list >> $GITHUB_STEP_SUMMARY
  fluentd:
    name: Scan Fluentd image with grype
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Get Target Image Name
        id: set_image_name
        run: |
          IMAGE=$(make echo-all-images | cut -d' ' -f1 | cut -d',' -f3)
          echo "IMAGE_NAME=$IMAGE" >> $GITHUB_OUTPUT
      - name: Scan Fluentd image
        uses: ./.github/actions/grype-scan
        with:
          image_name: fluent/fluentd:${{ steps.set_image_name.outputs.IMAGE_NAME }}
  # See https://github.com/docker-library/official-images/blob/master/library/ruby
  ruby:
    name: Scan Ruby image with grype
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Scan Ruby image
        uses: ./.github/actions/grype-scan
        with:
          image_name: ruby:3.4-slim
  # See https://github.com/docker-library/ruby/blob/master/3.4/slim-trixie/Dockerfile
  debian:
    name: Scan debian image with grype
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Scan Debian Trixie image
        uses: ./.github/actions/grype-scan
        with:
          image_name: debian:trixie-slim
