name: Windows
on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        include:
          # Even though dropped from GitHub Actions, but LTSC2019 itself is still maintained
          # - version: v1.19
          #   os-version: 2019
          - version: v1.19
            os-version: 2022
    runs-on: windows-${{ matrix.os-version }}
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          ruby-version: 3.4
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Build
        run: |
          ridk enable
          make image DOCKERFILE=${{ matrix.version }}/windows-ltsc${{ matrix.os-version }} VERSION=test
