name: Windows
on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        include:
          # Even though dropped from GitHub Actions, but LTSC2019 itself is still maintained
          # - version: v1.19
          #   os-version: 2019
          - version: v1.19
            os-version: 2022
    runs-on: windows-${{ matrix.os-version }}
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
        with:
          ruby-version: 3.4
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build
        run: |
          ridk enable
          make image DOCKERFILE=${{ matrix.version }}/windows-ltsc${{ matrix.os-version }} VERSION=test
